# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Flickr' do

  pod 'SwiftLint', '~> 0.47.1'

  target 'FlickrTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlickrUITests' do
    # Pods for testing
  end

end
